apiVersion: v1
kind: Pod
metadata:
  name: gp-v2

spec:
  containers:
    - name: solver
      image: gnosispm/gp-v2-services
      args: ["solver"]
      env:
        - name: PRIVATE_KEY
          value: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
        - name: AMM_SOURCES
          value: Uniswap

    - name: api
      image: gnosispm/gp-v2-services
      args: ["orderbook"]
      env:
        - name: DB_URL
          value: "postgresql://localhost/?user=me&password="
      ports:
        - hostPort: 8080

    - name: migrations
      image: gnosispm/gp-v2-services-migrations
      env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://localhost/?user=me&password="
      args: ["migrate"]

    - name: swapui
      image: gnosispm/gp-swap-ui
      ports:
        - hostPort: 8000

    - name: postgres
      image: docker.io/library/postgres:13.2
      ports:
        - hostPort: 5432
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_USER
          value: me

    - name: ganache-cli
      image: docker.io/trufflesuite/ganache-cli:v6.12.2
      args: ["-d", "-g", "0", "-l", "1e7", "-i", "5777", "--chainId", "1337"]
      ports:
        - hostPort: 8545
